update to 0.10.0 with 2025 pandoc
Co-authored-by: Jannik Volkland <volkland@sipgate.de>
Co-authored-by: Nick Garczorz <garczorz@sipgate.de>

diff --git a/app/pandoc-pretty-pdf-ex b/app/pandoc-pretty-pdf-ex
--- a/app/pandoc-pretty-pdf-ex
+++ b/app/pandoc-pretty-pdf-ex
@@ -1,10 +1,14 @@
 #!/bin/bash
+# experimental variant
+
 set -u  # undef is error
 set -e  # stop at error
 
 # added at version 1.5.5 but didnt work?
 #    --from markdown+auto_identifiers+backtick_code_blocks+bracketed_spans+definition_lists+emoji+example_lists+fenced_code_blocks+fenced_code_attributes+fenced_divs+footnotes+header_attributes+inline_code_attributes+inline_notes+link_attributes+pipe_tables+strikeout+subscript+superscript+table_captions+tex_math_dollars+yaml_metadata_block \
 #
+
+cat > /tmp/tmp.md
 
 pandoc \
     --from markdown+definition_lists+table_captions \
@@ -19,4 +23,12 @@ pandoc \
     -V toccolor=gray \
     -V 'code-block-font-size:\scriptsize' \
     -V 'table-use-row-colors:true' \
+    -o /tmp/tmp.pdf \
   "$@"
+
+if [ -f /tmp/tmp.pdf ]; then
+    cat /tmp/tmp.pdf
+else
+    echo "pandoc failed"
+    exit 1
+fi
